remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme 

layout: page

title: TechDeep Blog
description: Deep dive in to cutting edge technologies!

author:
  name: bade
  email: akshaybade12391@gmail.com

  social_links:
    - { platform: github,         user_url: "https://github.com/AkshayBade" }
    - { platform: linkedin,       user_url: "https://github.com/AkshayBade" }
